config:
  # Directory for database
  db-path: "./stats/"

  # The default statistic to be used for leaderboards
  default-leaderboard-statistic: "WIN"

  # The interval (in seconds) to save the db cache
  cache-save-interval: 36000